import os
import re
import subprocess
import threading

from avahi.service import Service
from avahi.types import HTTP


def unescape_unicode(text):
    """
    Unescape the Avahi-escaped representation of a string.

    :param text: String returned from the client Avahi call.
    :return: An Unicode-unescaped version of the string.
    """
    def replace(match):
        numeric, other = match.groups()
        if numeric:
            return chr(int(numeric[1:]))
        else:
            return other[1:]

    return re.sub(r'(\\\d\d\d)|(\\.)', replace, text.encode('ascii'))


def parse_txt(txt):
    """
    Parse a raw txt representation into a key-value map.

    :param txt: Txt string for a service returned from the client Avahi call.
    :return: A key-value map of all entries represented in the txt string.
    """
    def reduction(acc, val):
        key, value = val.split('=')
        # Remove the leading and trailing double quotes
        return dict(acc, **{key[1:]: value[:-1]})

    return reduce(reduction, filter(None, txt.split(' ')), {})


class AvahiClient(object):
    """
    Client for publishing and browsing Avahi-registered services.
    """

    def publish_service(self, name, type, port):
        """
        Publish a service in a background thread. The service will be automatically unpublished
        when the parent process exits.

        :param name: Name of the service.
        :param type: Type of the service; one of the constants from avahi.types.
        :param port: Port on which the service is running.
        """
        thread = threading.Thread(
            target=self._publish,
            args=(['-s', name, type, port],)
        )
        thread.start()

    def browse_services(self, local=True, service_type=HTTP):
        """
        Browse all discovered services.

        :param local: True to include locally published services; False to exclude locally published
                      services.
        :param service_type: The service type to discover; one of the constants in avahi.types.
        :return: An iterable of Service objects representing discovered services in the network.
        """
        shell_output = self._browse(filter(None, [
            '--resolve',  # Resolve into IP addresses
            '--ignore-local' if not local else '',
            '--parsable',  # Machine-parsable format
            '--no-db-lookup',  # Don't look up service type to speed lookup
            '--terminate',  # Don't hang forever
            service_type,
        ])).split('\n')

        resolved_services = (
            line.split(';')
            for line in shell_output
            if line and line.startswith('=')
        )

        return (
            Service(
                ip=service[7],
                name=unescape_unicode(service[3]),
                port=int(service[8]),
                txt=parse_txt(service[9]),
            )
            for service in resolved_services
            if service[2] == 'IPv4'
        )

    def _publish(self, flags):
        """
        Invoke the Avahi publish executable.

        :param flags: Flags to pass to the executable.
        :return: Stdout of invoking the publish executable.
        """
        return self._exec(['avahi-publish'] + flags)

    def _browse(self, flags):
        """
        Invoke the Avahi browsing executable.

        :param flags: Flags to pass to the executable.
        :return: Stdout of invoking the browse executable.
        """
        return self._exec(['avahi-browse'] + flags)

    def _exec(self, cmd):
        """
        Execute an arbitrary shell command, redirecting stderr to /dev/null.

        :param cmd: List of strings representing the shell command to execute.
        :return: Stdout generated by the command.
        """
        with open(os.devnull, 'w') as devnull:
            return subprocess.check_output(map(str, cmd), stderr=devnull)
